"""Initial migration

Revision ID: 46172cea144e
Revises: 
Create Date: 2026-04-26 09:23:50.468037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46172cea144e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'NEEDS_REVIEW', name='consultationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_transcript', sa.String(), nullable=True),
    sa.Column('clinical_data', sa.JSON(), nullable=True),
    sa.Column('wer_score', sa.Float(), nullable=True),
    sa.Column('clinical_score', sa.Float(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_facility_id'), 'consultations', ['facility_id'], unique=False)
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('consultation_id', sa.String(), nullable=True),
    sa.Column('asr_provider', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('raw_llm_response', sa.String(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Float(), nullable=True),
    sa.Column('output_tokens', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_consultation_id'), 'analysis_results', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_consultation_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_facility_id'), table_name='consultations')
    op.drop_table('consultations')
    # ### end Alembic commands ###
